name: "Install dependencies"
description: "Install and cache the dependencies"
runs:
  using: composite
  steps:
    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip/
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt')}}
    - name: Install dependencies
      run: pip3 install -r requirements.txt
      shell: bash
    - name: Install User Application dependencies
      run: pip3 install -r UserApplication/requirements.txt
      shell: bash
