name: "Install dependencies"
description: "Install and cache the dependencies"
inputs:
  submodule_dependency:
    description: "Install submodule dependencies"
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Setup cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip/
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt')}}
    - name: Install dependencies
      run: pip3 install -r requirements.txt
      shell: bash
    - name: Install User Application dependencies
      if: inputs.submodule_dependency == 'true'
      run: pip3 install -r UserApplication/requirements.txt
      shell: bash
