name: "CI CD Pipeline"
on: workflow_dispatch
jobs:
  Get Code:
    runs_on: ubuntu_latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Display file structure
        run: ls -lR
