name: "CI CD Pipeline"
on: [push, workflow_dispatch]
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        uses: ./.github/actions/InstallDependencies
      - name: Run Semgrep
        run: semgrep --config=auto --output ./output/semgrep_scan_results.json --json UserApplication
      - name: Upload Arfifact
        uses: actions/upload-artifact@v3
        with:
          name: sast findings
          path: ./output/semgrep_scan_results.json
      - name: Analyze findings
        run: python3 sast_analysis.py
  API_Testing:
    needs: SAST
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        uses: ./.github/actions/InstallDependencies
      - name: Run Api Tests
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
          POSTGRES_HOST: localhost
        run: python3 test_endpoints.py
  TrivyScanning:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          repository: git@github.com:shreyas-acharya/UserApplication.git
      - name: Install trivy
        run: wget https://github.com/aquasecurity/trivy/releases/download/v0.37.3/trivy_0.37.3_Linux-64bit.deb
      - name: Build docker image
        run: docker build -t userapplication-image -f UserApplication/Dockerfile .
      - name: Container Scanning
        run: trivy --format json --output ./output/trivy_scan_results.json image userapplication-image
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy findings
          path: ./output/trivy_scan_results.json
