name: "CI CD Pipeline"
on: workflow_dispatch
jobs:
  GetCode:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Display file structure
        run: ls -lR
