name: "CI CD Pipeline"
on: workflow_dispatch
jobs:
  SAST_Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        uses: ./.github/actions/InstallDependencies
