name: "CI CD Pipeline"
on: workflow_dispatch
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        uses: ./.github/actions/InstallDependencies
      - name: Run Semgrep
        run: semgrep --config=auto --output ./output/semgrep_scan_results.json --json UserApplication
      - name: Upload Arfifact
        uses: actions/upload-artifact@v3
        with:
          name: sast findings
          path: ./output/semgrep_scan_results.json
      - name: Analyze findings
        run: python3 sast_analysis.py
  API_Testing:
    runs-on: ubuntu-latest
    env:
      USERNAME: test
      PASSWORD: test
      DATABASE: test
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        uses: ././github/actions/InstallDependencies
      - name: Build containers
        run: docker compose -f ./UserApplication/docker-compose-yml up
