name: "CI CD Pipeline"
on: [push, workflow_dispatch]
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        uses: ./.github/actions/InstallDependencies
      - name: Run Semgrep
        run: semgrep --config=auto --output ./output/semgrep_scan_results.json --json UserApplication
      - name: Upload Arfifact
        uses: actions/upload-artifact@v3
        with:
          name: sast findings
          path: ./output/semgrep_scan_results.json
      - name: Analyze findings
        run: python3 sast_analysis.py
  API_Testing:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Update Submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        uses: ./.github/actions/InstallDependencies
      - name: Run Api Tests
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
          POSTGRES_HOST: localhost
        run: python3 test_endpoints.py
